name: Border Patrol
main: com.dpajd.ProtectionPlugin.Main.Main
version: "0.4b-dev"
author: calebbfmv
authors: [skore87]
softdepend: [Vault]
website: http://dev.bukkit.org/server-mods/border-patrol
description: Border Patrol is a Lightweight, advanced, grief protection, plugin! Allowing users, with the right Permission, to create protected land, and share it with friends!
commands:
    bp:
        aliases: [borderpatrol]
        description: 
        permission: BP.command.use
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bphelp:
        aliases: []
        description: Gives a command listing of Border Patrol
        usage: |
                /<command>
    bpcreate:
        aliases: []
        description: Creates a region protection
        permission: BP.command.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> [size] [-f][-p <protection>]
    bpaddflag:
        aliases: []
        description: Adds a protection flag to a region
        permission: BP.command.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <flag>
                
    bpremoveflag:
        aliases: []
        description: Adds a protection flag to a region
        permission: BP.command.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <flag>
        
    bpremove:
        aliases: []
        description: Removes a region protection
        permission: BP.command.remove
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bpbypass:
        aliases: []
        description: Bypasses region protection
        permission: BP.command.bypass
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bpcount:
        aliases: []
        description: Counts player region count
        permission: BP.command.count
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> [player]
    bpfaith:
        aliases: []
        description: Adds player to region members
        permission: BP.command.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <player>
    bpunfaith:
        aliases: []
        description: Removes player from region members
        permission: BP.command.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <player>
    bpsee:
        aliases: []
        description: See if chunk is protected
        permission: BP.command.use
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bptool:
        aliases: []
        description: Toggles use of the tool
        permission: BP.command.tool
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
                
    bpflags:
        aliases: []
        description: Lists all protections
        permission: BP.command.use
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    
permissions:
    # Command permissions
    BP.command.use:
        description: Allows use of /BP
    BP.command.tool:
        description: Allows use of the tool
    BP.command.count:
        description: Allows counting of regions
    BP.command.protect:
        description: Protect a region
    #BP.protect.limit.X:
    #    description: Limit protection count
    #BP.protect.limit.exempt:
    #    description: Exempt of limit protection count
    BP.command.see:
        description: View protections
    BP.command.remove:
        description: Allows removing protections
    BP.command.remove.self:
        description: Remove own protections
        children:
            BP.command.remove: true
        default: true
    BP.command.remove.others:
        description: Remove other protections
        children:
            BP.command.remove: true
            
    # Protection flag permissions
    BP.flag.WATER_FLOW:
        description: Prevent waterflow.
    BP.flag.LAVA_FLOW:
        description: Prevent lavaflow.
    BP.flag.ENTRY:
        description: Prevent entry to region.
    BP.flag.ELECTRIC:
        description: Prevent entry to region and shock.
    BP.flag.FIRE:
        description: Prevent fire burning and spreading.
    BP.flag.ENDERMAN:
        description: Prevent enderman grief.
    # BP.flag.WITHER:
        # description: FUTURE FLAG PROTECTION FOR NEW BOSS MOB
    # BP.flag.GHAST:
        # description: FUTURE FLAG PROTECTION FOR GHAST
    # BP.flag.DRAGON:
        # description: FUTURE FLAG PROTECTION FOR ENDER DRAGON
    BP.flag.MOB_DAMAGE:
        description: Prevent monsters damaging players and animals.
    BP.flag.MONSTER_SPAWNING:
        description: Prevent monster spawning in region
    BP.flag.PISTON:
        description: Prevent pistons altering protected regions.
    BP.flag.BUILD:
        description: Prevent building in region
    BP.flag.INTERACT:
        description: Prevent interacting in region
    BP.flag.PVP:
        description: Prevent PVP in region
    BP.flag.VEHICLES:
        description: Prevent vehicle placement in region
    BP.flag.CHEST_ACCESS:
        description: Prevent access to chests, furnaces, etc in region.
    BP.flag.FAREWELL:
        description: Adds a farewell message.
    BP.flag.WELCOME:
        description: Adds a welcome message.
        
    #Protection flag presets
    BP.flag.presets.messages:
        description: Allow messages to be sent on entry and exit of region.
        children:
            BP.flag.WELCOME: true
            BP.flag.FAREWELL: true
    BP.flag.presets.fluid:
        description: Prevent water and lavaflow.
        children:
            BP.flag.WATER_FLOW: true
            BP.flag.LAVA_FLOW: true
    BP.flag.presets.mob:
        description: Prevent Enderman, Wither, and dragon grief and damage.
        children:
            BP.flag.ENDERMAN: true
            #BP.flag.WITHER: true
            #BP.flag.ENDER_DRAGON: true
            #BP.flag.GHAST: true
            BP.flag.MOB_DAMAGE: true
    BP.flag.presets.mech:
        description: Mechanical event flags
        children:
            BP.flag.PISTON: true
    BP.flag.presets.modify:
        description: Prevent modifying region
        children:
            BP.flag.BUILD: true
            BP.flag.INTERACT: true
            BP.flag.VEHICLES: true
            BP.flag.CHEST_ACCESS: true
            BP.flag.USE: true
    BP.flag.presets.all:
        description: All flags
        children:
            BP.flag.presets.fluid: true
            BP.flag.presets.mob: true
            BP.flag.presets.mech: true
            BP.flag.presets.modify: true
            BP.flag.presets.messages: true
            BP.flag.ENTRY: true
            BP.flag.ELECTRIC: true
            BP.flag.FIRE: true
            BP.flag.PVP: true
            BP.flag.CHEST_ACCESS: true
            BP.flag.USE: true
    # User Presets
    BP.basic:
        description: Basic user
        children:
            BP.command.use: true
            BP.command.protect: true
            BP.command.remove.self: true
            BP.flag.presets.messages: true
            BP.flag.presets.modify: true
            BP.flag.presets.mech: true
            BP.flag.FIRE: true
            # BP.protect.limit.4: true
    BP.donator:
        description: Special donator privledges
        children:
            BP.basic: true
            BP.flag.presets.mob: true
            BP.flag.ELECTRIC: true
    BP.admin:
        description: The Bees knees!
        default: op
        children:
            BP.donator: true
            BP.flag.presets.all: true
            BP.command.see: true
            BP.command.count: true
            BP.command.tool: true
            BP.command.remove.others: true
            #BP.protect.limit.exempt: true
            BP.command.bypass: true