name: Border Patrol
main: com.dpajd.ProtectionPlugin.Main.Main
version: "0.3.1 Alpha"
author: calebbfmv
authors: [skore87]
website: http://dev.bukkit.org/server-mods/border-patrol
description: Border Patrol is a Lightweight, advanced, grief protection, plugin! Allowing users, with the right Permission, to create protected land, and share it with friends!
commands:
    bp:
        aliases: [borderpatrol]
        description: 
        permission: BP.use
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bphelp:
        aliases: []
        description: Gives a command listing of Border Patrol
        usage: |
                /<command>
    bpcreate:
        aliases: []
        description: Creates a region protection
        permission: BP.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> [size] [-f][-p <protection>]
    bpaddflag:
        aliases: []
        description: Adds a protection flag to a region
        permission: BP.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <flag>
                
    bpremoveflag:
        aliases: []
        description: Adds a protection flag to a region
        permission: BP.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <flag>
        
    bpremove:
        aliases: []
        description: Removes a region protection
        permission: BP.remove
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bpbypass:
        aliases: []
        description: Bypasses region protection
        permission: BP.bypass
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bpcount:
        aliases: []
        description: Counts player region count
        permission: BP.count
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> [player]
    bpfaith:
        aliases: []
        description: Adds player to region members
        permission: BP.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <player>
    bpunfaith:
        aliases: []
        description: Removes player from region members
        permission: BP.protect
        permission-message: You require <permission> to use this command!
        usage: |
                /<command> <player>
    bpsee:
        aliases: []
        description: See if chunk is protected
        permission: BP.see
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    bptool:
        aliases: []
        description: Toggles use of the tool
        permission: BP.tool
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
                
    bpflags:
        aliases: []
        description: Lists all protections
        permission: BP.use
        permission-message: You require <permission> to use this command!
        usage: |
                /<command>
    
permissions:
    BP.use:
        description: Allows use of /BP
    BP.tool:
        description: Allows use of the tool
    BP.count:
        description: Allows counting of regions
    BP.protect:
        description: Protect a region
    BP.protect.limit.X:
        description: Limit protection count
    BP.protect.limit.exempt:
        description: Exempt of limit protection count
    BP.see:
        description: View protections
    BP.remove:
        description: Allows removing protections
    BP.remove.self:
        description: Remove own protections
        children:
            BP.remove: true
        default: true
    BP.remove.others:
        description: Remove other protections
        children:
            BP.remove: true
        
    # User Presets
    BP.basic:
        description: Basic user
        children:
            BP.use: true
            BP.protect: true
            BP.remove.self: true
            BP.protect.limit.4: true
    BP.donator:
        description: Special donator privledges
        children:
            BP.protect: true
            BP.basic: true
    BP.admin:
        description: The Bees knees!
        default: op
        children:
            BP.donator: true
            BP.see: true
            BP.count: true
            BP.tool: true
            BP.remove.others: true
            BP.protect.limit.exempt: true
            BP.bypass: true